### ISSUE TITLE
Installation not working, launchers not added to Steam library

### ISSUE THREAD

**Issue by alvarobrod** [moraroy/NonSteamLaunchers-On-Steam-Deck#166]
I've been trying to download and install different launchers on my Steam Deck, namely Epic Games launcher, EA App and Rockstar Games Launcher. 
Whenever the installation finishes, both the EA App and the Rockstar Games Launcher launch normally, but not the Epic Games one. But if I close any of them, I do not have any way of launching them again as they are not added to my Steam library.
Looking at the installation log, this is the last thing I see:
```
Traceback (most recent call last):
File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 235, in <module>
with open(f"{logged_in_home}/.steam/root/userdata/{steamid3}/config/shortcuts.vdf", 'rb') as file:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.steam/root/userdata//config/shortcuts.vdf'
```

I have tried to install those three launchers, just the Epic Games one, tried the 3.0 version, then tried the 3.2 version and it's the same for me, can't get anything installed apparently.

Would love to get some help about this, thanks for your work!
Cheers.

**Comment by moraroy** [comment]
@alvarobrod send your full log it's not finding your steamid

**Comment by moraroy** [comment]
@alvarobrod thanks brother you can delete the link if you wish, it has to do with a syntax error when trying to find your Steam ID,  I'll be able to update it tomorrow or so, that was very helpful info thank you

**Comment by spkane** [comment]
I think I also have the same issue with 3.2. I'll give the new version a try when it is ready to test and/or released.

**Comment by moraroy** [comment]
@spkane I fixed it

**Comment by spkane** [comment]
> @spkane I fixed it

I just tested this and I am seeing new launcher entries. I'll try and get logged into each of them and do a little more testing, but this specific issue appears to be fixed. Thanks!

**Comment by alvarobrod** [comment]
I can also confirm the entries are showing up on the Steam Library. Thank you for the quick fix!

**Comment by jlht01** [comment]
Hello! I'm new to Linux through my Steam Deck and having the same issue. Epic is the only launcher not working. I tried redownloading the nonsteamgames launcher since it sounds like the code was updated, but the issue persists. Can you help?
