### ISSUE TITLE
Games are not added or not working

### ISSUE THREAD

**Issue by Cr0wTom** [moraroy/NonSteamLaunchers-On-Steam-Deck#209]
Thank you for this amazing tool. Made my deck 1000x better.

But one issue I have is that it's inconsistent with the games added.

- All Launchers installed successfully.
- Most Chrome clients (Disney, Prime, etc.) installed successfully.
- Game Control, installed successfully from Epic, parsed successfully after reboot and plays properly from SteamOS
- Game Fallout, installed successfully from GOG, parsed successfully after reboot, but does not run from SteamOS. The game directly stops (button becomes green) but game runs from inside the launcher.
- Game It Takes Two, installed successfully from EA, it is not parsed at all and I tried everything. The game runs from inside the launcher.
- When I try to install Netflix or tv.apple.com as a custom link, it's not adding anything on the Steam.

I am also attaching my log, I would appreciate some help, and if needed I can help debugging the issue further.

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14276898/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@Cr0wTom interesting OK thank will continue to look at the coding. Each scanner has its individually way of parsing in the NSLGameScanner.py file

**Comment by sysmoon14** [comment]
Couple of questions @Cr0wTom:

1. Does the Fallout shortcut in Steam have a Proton version assigned to it? You can see this if you go to "Properties" -> "Compatibility"
2. For It Takes Two, did you change the install directory when installing from the EA App? Can you confirm what the directory is?

**Comment by Cr0wTom** [comment]
> Couple of questions @Cr0wTom:
> 
> 1. Does the Fallout shortcut in Steam have a Proton version assigned to it? You can see this if you go to "Properties" -> "Compatibility"
> 2. For It Takes Two, did you change the install directory when installing from the EA App? Can you confirm what the directory is?

Yes, it has, and I also tried changing the Proton version, but in the end it doesn't even make sense as inside GOG it runs correctly with the GOG assigned Proton.

Directory is in the SD card, and it's the one I selected during installation from inside EA, didn't move the game, but yes I changed from the default during installation.

**Comment by sysmoon14** [comment]
@Cr0wTom thanks for confirming.

1. Can you grab the contents of the Fallout shortcut please? Target, Start In, and Launch Options would be great.
2. That's definitely the issue, currently the EA scanner is just looking in the default install directory. We'll see if we can make that smarter somehow.

**Comment by Cr0wTom** [comment]
> @Cr0wTom thanks for confirming.
> 
> 1. Can you grab the contents of the Fallout shortcut please? Target, Start In, and Launch Options would be great.

- Target: "/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe"
- Start In: "/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/GOG Galaxy/"
- Launch Options: STEAM_COMPAT_DATA_PATH="/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/" %command% /command=runGame /gameId=1440148836 /path="\"

These are the default contents, I did not change anything.

> 2. That's definitely the issue, currently the EA scanner is just looking in the default install directory. We'll see if we can make that smarter somehow.

OK, though I did this with both the Epic and GOG and it worked.

**Comment by sysmoon14** [comment]
Ok @moraroy, I think it's the same root issue with both Fallout and It Takes Two. I've installed Fallout on my deck to the default directory and it works fine, but @Cr0wTom's shortcut is totally missing the "/path=" argument in the launch options.

**Comment by moraroy** [comment]
@sysmoon14 yeah I noticed that, I think we have to derive the path from the registry, everyone's uuid is different for their SD card, which it would need to be translated to a lettered path for example path=D:

**Comment by Cr0wTom** [comment]
> Ok @moraroy, I think it's the same root issue with both Fallout and It Takes Two. I've installed Fallout on my deck to the default directory and it works fine, but @Cr0wTom's shortcut is totally missing the "/path=" argument in the launch options.
> 
> So shortcuts don't work for GoG or EA if they're not installed in the default directories.

True, changing the path, fixed the issue on the Fallout.

**Comment by sysmoon14** [comment]
@Cr0wTom, the GoG issue should now be fixed. It should work regardless of where you installed it. You'll need to make sure it's using the latest version of the script from the git repo

**Comment by moraroy** [comment]
@Cr0wTom has this since been fixed for you? Also please confirm if your cloud saves and local saves still work. I was under the impression that in order for the shortcut to work it needed that path in the launch options. When it comes to Gog, you can run the .exe straight from the directory because there is no DRM. However doing so, doesn't allow for the cloud saves and local saves to sync via the gog Launcher. Just wanted to make sure now if the gog Launcher was being opened in the background of your games and they are syncing for both cloud and local saves!

**Comment by Cr0wTom** [comment]
I basically fixed it by adding the appropriate path on the Launch Options, so it runs properly by launching GOG on the backround. 

I did the same on the EA game from the SD. So basically as you said the only issue to fix, is to find a way to discover the unique SD card ID of each target SD. 

I guess for this **dmesg** or **fdisk -l** should work, but I don't have my Deck in front of me now to propose the proper way of doing it. I will follow up.

**Comment by moraroy** [comment]
@sysmoon14 I'm not sure if the path is needed anymore?

**Comment by labree0** [comment]
I think im still having this same issue. I installed Hollow Knight from GOG and it did not even have a "/path=""" thing, and when attempting to launch the game it just failed. Using the default directory or installing it elsewhere did not change anything. I've used the newest proton from valve and the newest GE proton as well. I am not installing on an SD card, and whether i install to the default GOG Games directory to straight to the "root" drive, at C:/HollowKnight, makes no difference. I have not made any changes to the launch commands, target, or start in directory.

I can put those in here, but its a bit of a pain to get them off the steam deck.

**Comment by KyleStilkey** [comment]
> I think im still having this same issue. I installed Hollow Knight from GOG and it did not even have a "/path=""" thing, and when attempting to launch the game it just failed. Using the default directory or installing it elsewhere did not change anything. I've used the newest proton from valve and the newest GE proton as well. I am not installing on an SD card, and whether i install to the default GOG Games directory to straight to the "root" drive, at C:/HollowKnight, makes no difference. I have not made any changes to the launch commands, target, or start in directory.
> 
> I can put those in here, but its a bit of a pain to get them off the steam deck. If i go straight to the executable "Hollow Knight.exe" and add it to steam and use proton, it works fine. It also boots through GOG, but the shortcut created by the script in steam just wont launch. It just switches to "Cancel" and then immediately goes back to "play".
> 
> Edit: just tested - cloud saves don't work if I launch it through the executable. Likely because of the different virtualized directories, unfortunately.
> 
> Target: "/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (X86)/GOG Galaxy/GalaxyClient.exe" Start in: "/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (X86)/GOG Galaxy/"
> 
> Launch options: STEAM_COMPAT_DATA_PATH="/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/" %command% /command=runGame /gameId=1308320804"
> 
> The game is not installed in an SD card, either. Its installed in the default installation directory.

Same exact issue here, if I install it all as default and use the defaulted created entry, it's the same as above for all my GOG games. Changing to the direct .exe works fine as normal but this command launch method doesn't seem to be working at all for me.

**Comment by sysmoon14** [comment]
Ok reverted the change and now the path is added to GOG games. This will only work for games that are installed in the default GOG directory though.

**Comment by labree0** [comment]
Sure. I managed to fix the issue by just adding a /path="_<Your game install directory>_" option at the end of the launch options. That got the game to boot through GOG even when i selected a different install directory. One day i'll have to figure out how to install games to the SD card and do this, but I don't have an SD card at the moment.

Still a fantastic app, super convenient. Wish steam would let us edit non-steam metadata, but oh well.

**Comment by meme1337** [comment]
Hi @moraroy, and thanks for your tool!
Got rid of Lutris and Heroic in one sweep :smile: 

I had issues with not having games added as well, and via a bit of investigation I found the reason, at least on my system.
I had installed HITMAN3 via EGL. The game comes with addons installed, and it seems that the script tries to parse them as well as standalone games.
For the other addons map it was able to find a match on boilr (even if it didn't make sense), but for one specific, ` Chongqing`, the python script was crashing and that lead to games not being added.
I "solved" on my system by removing the addon, and then restarting the NSLscanner.

Maybe this could be a reason for the issues other users are having.
