### ISSUE TITLE
The launchers don't show up in Steam library

### ISSUE THREAD

**Issue by DylanDouglas93** [moraroy/NonSteamLaunchers-On-Steam-Deck#27]
I can't manage to get the launchers to show up in my Steam Library. I have tried it on Steam Stable and Steam Beta with no difference in results. i have tried to get this to work many times with no success. I hope you can make an update with a fix for those us of with this issue @moraroy

**Comment by moraroy** [comment]
@DylanDouglas93 rest assured I'm looking into all of these errors. I've had IRL things going on and haven't been able to update in a while. But don't worry I'm looking into to fixing everything.

**Comment by stumbiers** [comment]
same thing for me.

**Comment by dnolder** [comment]
Yep, same issue, even if I try to add non-Steam game manually in Steam.

**Comment by mthbrown** [comment]
Same here

**Comment by moraroy** [comment]
@mthbrown @dnolder @DylanDouglas93 @stumbiers @cchrkk I've updated part of the fix to 2.75 that may help some people. I will be updating to 2.8 in a couple of days with the rest of it. The other part of the code will completely get rid of "setup tools" and do things the right way.

**Comment by dnolder** [comment]
Unfortunately, 2.75 didn't help me. I'll wait for 2.8. Thanks anyway.

**Comment by mthbrown** [comment]
@moraroy Thanks. My feedback was actually on v2.75 so unless I'm missing something, I don't think it was resolved in v2.75

**Comment by moraroy** [comment]
@mthbrown @dnolder @DylanDouglas93 @stumbiers @cchrkk  2.8 is out let me know whats up

**Comment by dnolder** [comment]
Still not appearimg in my Steam library with 2.8.

**Comment by moraroy** [comment]
@dnolder can you send me a log?

**Comment by dnolder** [comment]
[nsl.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11581202/nsl.log)

**Comment by moraroy** [comment]
@dnolder I need the log after that part of the code.

**Comment by dnolder** [comment]
Where can I find it?

**Comment by moraroy** [comment]
It should be there.. it should be in the Konsole

**Comment by dnolder** [comment]
Sorry, the Konsole closes when it finishes, so I had to run it manually.
[nsl2.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11581239/nsl2.log)

**Comment by mikssj3** [comment]
@moraroy Same issue for me as well

**Comment by moraroy** [comment]
@mikssj3 @dnolder i thank you that was helpful try the latest download i  updated the script just now

**Comment by dnolder** [comment]
Sill no joy here.

**Comment by anders-kaffia** [comment]
I have the same issue. Thanks @moraroy for working on this 🙂🎈

**Comment by moraroy** [comment]
Send me your logs again @dnolder

**Comment by mikssj3** [comment]
@moraroy tried the updated script but the result is the same unfortunately

**Comment by moraroy** [comment]
@mikssj3 could you send a log?

**Comment by dnolder** [comment]
Here yoo go ...

[nsl3.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11581347/nsl3.log)

**Comment by moraroy** [comment]
@dnolder thank you that gave me good info... basically it's erroring out with the steam user iID. Try downloading the NonsteamLaunchers.sh file one last time I updated 1 line of code to maybe fix this issue. I can see in your log that I fixed the .zip issue so hopefully this will do it. Thank you all for being patient with me haha

**Comment by dnolder** [comment]
Thanks for your work on this, unfortunately no change.

[nsl4.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11581571/nsl4.log)

**Comment by Kaabvoo** [comment]
Can a work around might be downloading the version 2.71 or 2.7? Have someone test that option?

**Comment by stixxyz** [comment]
Even if trying to add the launchers to steam manually it doesn't work like it's supposed to.

**Comment by moraroy** [comment]
@stixxyz @Kaabvoo @dnolder i updated the script again so you have to grab the new ".sh" file. I wont update the release to 2.9 until i resolve these errors. let me know how this one goes.

**Comment by Kaabvoo** [comment]
@moraroy I just check the.desktop file and what it does (I assume) it runs content of the..sh of the branch main therefor I just run the.desktop file and tried to run install the Amazon games and it didn't work so I assume it's not done yet

My steps to reproduce are
1.- Make a fresh start
2.- Install Amazon games only (for speedy test)
3.- check steam and still not appearing 😅

If you make a new push let me know so I can test it 😉

Thanks BTW!

PD. If I knew Bash I might help on the code 😔😔

**Comment by moraroy** [comment]
@Kaabvoo log?

**Comment by moraroy** [comment]
@Kaabvoo i updated to 2.81 if it doesnt work can you send me a log?

**Comment by Kaabvoo** [comment]
sure thing
i just tested it and still nothing let me include the log
[log.txt](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11583885/log.txt)

**Comment by moraroy** [comment]
@Kaabvoo need the code after that in the konsole

**Comment by slmtik** [comment]
[log.txt](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11584191/log.txt)

**Comment by xaguzman** [comment]
Same issue here.
For everybody facing this issue, I tried with version 2.6 and that one did correctly add my shortcuts to the steam store.

@moraroy Didnt take the time to see what changed between v2.6 and 2.75+, but the usage of the python package vdf broke.

**Comment by mikssj3** [comment]
@xaguzman no matter what version we download, when we open the executable file it's always on 2.8 and still doesn't work

**Comment by Tanamachii** [comment]
Just change the line of code "Exec=sh -c 'curl -L https://raw.githubusercontent.com/moraroy/NonSteamLaunchers-On-Steam-Deck/main/NonSteamLaunchers.sh | bash'" of the file NonSteamLaunchers.desktop to "Exec=sh -c 'curl -L https://raw.githubusercontent.com/moraroy/NonSteamLaunchers-On-Steam-Deck/c9f7123/NonSteamLaunchers.sh | bash'" and that would install 2.6 version when execute the file :), that worked for me

**Comment by JayJayJohnson** [comment]
@mikssj3 just make the NonSteamLaunchers.sh (2.6) executable and run it.

It works. Just testet ist. 2.8.1 does not work.

**Comment by mthbrown** [comment]
Can confirm that downloading and using 2.6 with the one-line modification mentioned by @Tanamachii works

**Comment by artinnok** [comment]
@xaguzman @moraroy I also confirm that 2.6 works flawlessly without any changes made into source code.

I tried 2.81 but it doesn't work - Python can't find `vdf` package and fails.

BTW, @moraroy thank you so much for this script 👍

**Comment by SuperChaoHai** [comment]
HI i am on SteamOS 3.4.6
i downloaded source 2.81 (latest)
i click start fresh because previously i tried 2.8 but the launcher didnt show on the library 
then after that i re launch the 2.81 
and select Battle.net and Epic game.
let it run several minutes until yoda's contempelation
after that check steam library, no launcher 
please help @moraroy

**Comment by moraroy** [comment]
@SuperChaoHai @artinnok @mthbrown @JayJayJohnson @Tanamachii @xaguzman  i just updated to 2.82, let me know if it works now, if not ill roll back to 2.6 in regards to "setup tools."

**Comment by SuperChaoHai** [comment]
HI @moraroy 
nope it doesnt work this is what i did
launch 2.82
click start fresh (it will close)
launch 2.82 again
select battle.net and epic game
let it run until contempelation
click ok everything will close
steam will auto open, check library..
empty ... 😄

**Comment by moraroy** [comment]
@SuperChaoHai can you send me a log?

**Comment by Kaabvoo** [comment]
@SuperChaoHai Yep me too it didn't work

@moraroy i tried the "rollback" from @Tanamachii and it worked the thing is that in epic games didn't work the keyboard while trying to log in 😔 but including the launchers in the steam library it's working 😉

**Comment by moraroy** [comment]
Well it's good, because it shows that I fixed the steam ID bug I had it seems like most people have that fixed now if 2.6 seemed to work. , but I was very much attempting to get rid of "setuptools" going forward :(

**Comment by cchrkk** [comment]
You should use branches so we can have multiple launchers to use the stable (2.6) or the testing (2.8) versions 😂

**Comment by moraroy** [comment]
@cchrkk dang youre right, me updating and failing is getting ridiculous haha im sorry guys, im on 2.83 now

**Comment by SuperChaoHai** [comment]
i am so sorry noob here
i wish to help you as much as i can
how to get you the log before i attempt 2.83

**Comment by moraroy** [comment]
@SuperChaoHai right click it and have it "run in Konsole" but i would update and grab 2.83 and then see if it works. most likely its the same error from 2.82 if it doesnt work

**Comment by SuperChaoHai** [comment]
sorry i tried to get the log by right click and run in konsole but it just a prompt and i am not sure what to key in HAHAHA
so i do everything again
i downloaded 2.83
then start fresh
then install epic and battle
and this time it is in my steam library !!
and battle.net install without problem after i choose the ge-pronton

**Comment by moraroy** [comment]
@SuperChaoHai LETSS GOOOOOO!!!!!!!!

**Comment by cchrkk** [comment]
I will try to edit the desktop file and make It create a log file by default

**Comment by moraroy** [comment]
@cchrkk heck yeah that would be tight... im just glad its working now im sorry this took a long time. i hope this will work for most people thank you @SuperChaoHai for hanging in there haha

**Comment by moraroy** [comment]
@cchrkk thank you for always helping make the script better btw! youre a good friend and a big help!

**Comment by mikssj3** [comment]
I must be doing something wrong because no matter what version I try, 2.6, 2.83 the launchers never get added

**Comment by moraroy** [comment]
@mikssj3 can you send me a log?

**Comment by moraroy** [comment]
@mikssj3 I need the rest of the log after that part of the script..also for some reason it says Rockstar has failed to install for some reason... interesting..

**Comment by dnolder** [comment]
2.83 works for me now. Thanks for your work on this.

**Comment by mikssj3** [comment]
@moraroy how can I save that part of the code since the window closes automatically when finished? sorry for my ignorance

**Comment by moraroy** [comment]
@mikssj3 right click the .sh file and "run in "konsole"

**Comment by mikssj3** [comment]
Warning: Could not find '/home/deck/Downloads/NonSteamLaunchers-On-Steam-Deck-2.83/NonSteamLaunchers.sh', starting '/bin/bash' instead.  Please check your profile settings.

I get this error and it doesn't run

**Comment by moraroy** [comment]
@mikssj3 make sure when you right click it, you also set it to "execute" in the second tab of the properties menu.

**Comment by mikssj3** [comment]
Perfect, ty. Here goes
[log.txt](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11591073/log.txt)

**Comment by moraroy** [comment]
@mikssj3 ah.. OK I see what's going on. I'll be able to fix this in the morning thank you for showing me.

**Comment by mikssj3** [comment]
@moraroy glad to help 😉. Looking forward to it

**Comment by moraroy** [comment]
@mikssj3 @mthbrown @xaguzman @dnolder @artinnok @slmtik @cchrkk @xaguzman @anders-kaffia @Tanamachii @stixxyz let me know what you guys think of 2.84. I want to make sure these launcher are in your library that way i can start fixing other bugs.

**Comment by SuperChaoHai** [comment]
@moraroy do u want me to run it and test for u ?

**Comment by moraroy** [comment]
@SuperChaoHai sure yeah... i mostly wanted to see if the fix for @mikssj3 was fixed, also things should be still working on your end on 2.84, mostly likely if 2.83 worked on your end. the next update should still work i dont believbe ive broken anything except added more checks to make sure everything is needed to run the .py files.

**Comment by SuperChaoHai** [comment]
@moraroy so let me get the steps right..
i am currently on 2.83 and i have installed battle.net and epic 
both launcher appear on my library.
I have successfully installed both battle.net and epic client on steam deck

if i were to do testing for you
i should click FRESH START , then relaunch and proceed as normal , right?
will clicking FRESH Start to delete the installed battle.net and epic client? so i can do a clean testing for u

**Comment by moraroy** [comment]
@SuperChaoHai no you don't have to do that... you can just delete the Library Entry's in the steam library and that's it. Then run 2.84 and select the launchers you have installed already this will skip the installations and add them straight to steam.

**Comment by SuperChaoHai** [comment]
@moraroy
i deleted the epic and battle entry from steam library
right click change propertise of .sh to executable
right click run in konsole
select only epic and battle.net (it already have existing path)
click OK
steam client re-launch
epic and battle.net entry is there
here is the log file

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11595470/NonSteamLaunchers-install.log)

**Comment by DylanDouglas93** [comment]
> @DylanDouglas93 rest assured I'm looking into all of these errors. I've had IRL things going on and haven't been able to update in a while. But don't worry I'm looking into to fixing everything.

I have just installed 2.84 and that appears to have added the launchers to my Steam library. Excellent work man. I appreciate the quick support

**Comment by stixxyz** [comment]
@moraroy 2.83 ia working fine for me, thanks for this!

**Comment by mikssj3** [comment]
Hi @moraroy . I'm sorry to inform that it still doesnt't work for me 😔
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11597706/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@mikssj3 :( i just updated the .sh file i changed the code to install it more specifically hopefully it will work this time.. try downloading the .sh file again and see if that helped.

**Comment by mikssj3** [comment]
it doesn't run. I get this error:

Warning: Could not start program '/home/deck/Downloads/NonSteamLaunchers-On-Steam-Deck-2.84/NonSteamLaunchers.sh' with arguments ''.

Warning: execve: Exec format error

**Comment by moraroy** [comment]
@mikssj3 you gotta right click and set to execute! you have to do that when you download the .sh file by itself! if you use the desktop file you dont have to do that.

**Comment by mikssj3** [comment]
I did exactly that. The outcome is that error :/

**Comment by mikssj3** [comment]
@moraroy i
 tried opening the sh with Kate. It seems to be related with limit:

"The file /home/deck/Downloads/NonSteamLaunchers-On-Steam-Deck-2.84/NonSteamLaunchers.sh was opened and contained lines longer than the configured Line Length Limit (10,000 characters).
The longest of those lines was 398,135 characters long
Those lines were wrapped and the document is set to read-only mode, as saving will modify its content."

**Comment by markylad** [comment]
Now works on the latest update, thank you.

**Comment by moraroy** [comment]
@mikssj3 were able to to get the script working im alittle confused on why that error popped up tbh lol

**Comment by mikssj3** [comment]
@moraroy I really don't know. I tried everything already. It's a shame but oh well. Thanks anyway for trying

**Comment by moraroy** [comment]
@mikssj3 no! im not giving up! im going to fix it.

**Comment by SuperChaoHai** [comment]
@moraroy new problem... after doing the 2.84 and it is installed...
i thought all done.. but actually the launcher doesnt launch even with correct proton selected.
now i am trying to reinstall again :smile:

**Comment by SuperChaoHai** [comment]
> @moraroy new problem... after doing the 2.84 and it is installed... i thought all done.. but actually the launcher doesnt launch even with correct proton selected. now i am trying to reinstall again smile

i downloaded 2.83
run it again... only select epic and battle net
press OK

and battlenet launcher launch after installation

**Comment by mikssj3** [comment]
Hi @moraroy any update? it's still not working for me

**Comment by moraroy** [comment]
@mikssj3 use the latest and send the log I want to see the differences between before and now because all of the code has changed since then

**Comment by Tekka90** [comment]
I freshly reimaged my deck, and got the same error :( here is my log file
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11688306/NonSteamLaunchers-install.log)

**Comment by alexlv4** [comment]
Hi, sane issue with 2.94 and 2.95 same error

`Loaded Config for Local Selection Path for App ID 413080, Controller 15: controller_base/desktop_neptune.vdf
BRefreshApplicationsInLibrary 1: 1ms
roaming config store loaded successfully - 335 bytes.
migrating temporary roaming config store
Loaded Config for Local Selection Path for App ID 413080, Controller 15: controller_base/desktop_neptune.vdf

(steam:14252): GLib-GObject-CRITICAL **: 11:24:04.638: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:14252): GLib-GObject-CRITICAL **: 11:24:04.638: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(steam:14252): GLib-GObject-CRITICAL **: 11:24:04.694: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:14252): GLib-GObject-CRITICAL **: 11:24:04.694: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
System startup time: 5.41 seconds
!! Controller 15 attributes:
  Type: 4
  ProductID: 4613
  Serial: FXAA22201B22
  Capabilities: 0160bfff
  Firmware Version: 0
  Firmware Build Time: 1669064275 (Mon, 21 Nov 2022 20:57:55 GMT)
  Bootloader Build Time: 1647291078 (Mon, 14 Mar 2022 20:51:18 GMT)
BuildCompleteAppOverviewChange: 158 apps
RegisterForAppOverview 1: 11ms
RegisterForAppOverview 2: 11ms
ExecCommandLine: "'/home/deck/.local/share/Steam/ubuntu12_32/steam' '-steamdeck'"

(steam:14252): GLib-GObject-CRITICAL **: 11:24:07.075: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:14252): GLib-GObject-CRITICAL **: 11:24:07.075: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Loaded Config for Local Selection Path for App ID 1794680, Controller 15: /home/deck/.local/share/Steam//controller_base/templates/controller_neptune_gamepad_fps.vdf
Loaded Config for Local Selection Path for App ID 413080, Controller 15: controller_base/desktop_neptune.vdf
Loaded Config for Local Selection Path for App ID 413080, Controller 15: controller_base/desktop_neptune.vdf

(steam:14252): GLib-CRITICAL **: 11:24:11.365: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:14252): GLib-CRITICAL **: 11:24:11.365: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
Loaded Config for Local Selection Path for App ID 1677740, Controller 15: /home/deck/.local/share/Steam//controller_base/templates/controller_neptune_gamepad_joystick.vdf

(steam:14252): GLib-CRITICAL **: 11:24:21.376: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:14252): GLib-CRITICAL **: 11:24:21.376: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed

(steam:14252): GLib-CRITICAL **: 11:24:31.382: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:14252): GLib-CRITICAL **: 11:24:31.382: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed

(steam:14252): GLib-CRITICAL **: 11:24:41.425: g_main_context_push_thread_default: assertion 'acquired_context' failed`

**Comment by alexlv4** [comment]
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11807764/NonSteamLaunchers-install.log)

**Comment by faith0811** [comment]
Not working at the latest v2.95. After manually installing v2.83, the launcher appears in the steam lib.

**Comment by moraroy** [comment]
@faith0811 apparently people have been using this version isntead of all the news ones since then, and according to some people on reddit there is a typo somehwere, im trying to track it down
