### ISSUE TITLE
Cannot install any launchers.

### ISSUE THREAD

**Issue by AdamSpike** [moraroy/NonSteamLaunchers-On-Steam-Deck#619]
Hello. I recently downloaded Decky along with the NSL Plugin but any time I try to install the Rockstar and Ubisoft launchers, they do not install despite the popup saying they've been successfuly installed.

I installed the PokeRogue site without any issues but it is just the launchers that don't work.

I've tried uninstalling and reinstalling and clicking start fresh but nothing seems to work.

**Comment by moraroy** [comment]
@AdamSpike are you on stable steamos? Or decky loader?

**Comment by AdamSpike** [comment]
You'll have to forgive me because I'm fairly new to the Steam Deck.

I installed Decky on to the Steam Deck and then downloaded the NSLplugin and installed it to Decky using that. When I access Decky through Gaming Mode and go to the NSL plugin and try to install the launchers, that's when the problem starts.

**Comment by moraroy** [comment]
@AdamSpike did you run a "manual scan"? Or what colors are the launchers? Red or green?

**Comment by AdamSpike** [comment]
The launchers stay red even though the pop-up says 'successfully installed' after pressing install.

The install window doesn't even come up like it did when I installed PokeRouge. It flashes up for a second then disappears and says installed.

**Comment by moraroy** [comment]
@AdamSpike yeah that is weird, on mine it seems to be running fine... are you on any sort of beta or anything? If not, uninstall NonSteamLaunchers, and download the "NSLPlugin.desktop" from the github. And see if that fixes anything. Let me know!

**Comment by AdamSpike** [comment]
Not that I'm aware of.

I did a reinstall the way you suggested but still no luck at all. I ended up installing the desktop version which seems to have worked thankfully!

**Comment by moraroy** [comment]
@AdamSpike ok thanks for letting me know, you can jump back into game mode and things should be working now I. The plugin version. Ilk take a look maybe I messed up somewhere

**Comment by AdamSpike** [comment]
Thanks for the help, mate!

**Comment by twistthoseknobs** [comment]
Hi I'm experiencing the same issue. I am on stable steam, stable decky and latest NSL. Says installed, status button remains red and no icon in steam even after Manual Scan. I have tried reinstalling NSL and decky but still not working.

**Comment by moraroy** [comment]
@twistthoseknobs this fixed with theater updates I've made?

**Comment by gergoke68** [comment]
I have succeeded in installing every launcher after selecting "separate launcher folders".

**Comment by twistthoseknobs** [comment]
@moraroy at the time I was also experiencing the issue of GOG Galaxy unable to install games so I ended up factory resetting, just a few hours after my comment, which fixed all my issues...
