### ISSUE TITLE
GOG Galaxy - Incorrect free disk space

### ISSUE THREAD

**Issue by samdevega** [moraroy/NonSteamLaunchers-On-Steam-Deck#835]
## 🐛 Bug Description
GOG Galaxy app is not determining the free disk space properly. It says that there is no enough space in the disk when actually is.

**Which version are you using?**  
- [x] NonSteamLaunchers.desktop (Desktop Version)
- [x] Decky Plugin (`NonSteamLaunchersDecky`)

---

## 🔁 To Reproduce
1. Create a new partition in a secondary disk:
* File system: btrf.
* Permissions: allow everyone.
2. Mount the partition over /mnt/games or similar.
3. In GOG Galaxy app, set the secondary disk directory or a subdirectory within it as Downloads directory for installing games (I set /mnt/games/SteamLibrary/steamapps/common)
4. In GOG Galaxy app, select a purchased game and click install.
5. Observe the issue.

---

## ✅ Expected Behavior
GOG Galaxy should not show any error related to not having enough space in a disk which clearly has it. It should allow to install a game as expected.
I was able to install a game from another launcher (Epic Games) in the same path, so a r/w permission issue is discarded.

---

## 🖼️ Screenshots / Logs
Screenshots: https://imgur.com/a/8iFTQ95

---

## 🧰 System Information
**Device Type**
- [x] Desktop PC

**Operating System**
- [x] Other Linux Distro: Fedora KDE 43

**Details**
- **Steam Version:** 1763795278
- **Kernel Version:** 6.17.9-300.fc43.x86_64
- **Proton Version Used:** Proton GE 10.25
- **Launchers Affected:** GOG Galaxy 2.0.74.352 - Beta (installed by NSL script, not updated by app itself)
- **NSL Version:** 4.2.76 Desktop / 1.2.80 Decky Plugin
- **Install Method:** Script (.sh) / Desktop Launcher (.desktop) / Decky Plugin  

---

## 💬 Additional Context
Add any other context about the problem here, such as:
- [x] Reinstalling NSL did not fix the issue
- [x] Clearing compatibility data did not help
- [x] I am using a custom Proton build (GE)

Provide any temporary fixes or additional details below:
- Fix not yet found.

**Comment by moraroy** [comment]
@samdevega ill be honest with you I havnt come across that issue yet because I dont have a separate partition when I play my games on the steam deck... I remember back when the steamdeck came out... there was a github project that would mount partitions and other things properly so that Proton can see them. I forgot what it was called, but it kind of sounds like thats what is happening, its a Proton/mounting issue.

**Comment by moraroy** [comment]
@samdevega another question I have, is the gog launcher updated all the way or did you skip the gog launcher update when it asked.

**Comment by samdevega** [comment]
>I remember back when the steamdeck came out... there was a github project that would mount partitions and other things properly so that Proton can see them...

I see. I will look for more information related to this.

>is the gog launcher updated all the way or did you skip the gog launcher update when it asked.

I tried both approaches. Let the GOG version untouched at first launch after the NSL install script and also letting the launcher update by itselt. The issue is present in both cases.

**Comment by moraroy** [comment]
@samdevega ok.. yeah not sure. It may simply be just a gog launcher problem. Let me know if you find out any more info.

**Comment by samdevega** [comment]
I found a workaround to deal with the issue. Instead of trying to set the games installation folder directly to a folder in the secondary disk, I created a symlink in the primary disk within the compatdata folder (~/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser) so now there is a new "folder" called Games that points to the Steam library folder in the secondary disk (/mnt/games/SteamLibrary/steamapps/common).
Rest of folders are pointing to games installation folder by default.

Could I suggest to include an extra option in the NSL install menu to choose where do you want to install the launchers so their downloads folders will be in the desired disk? Is that a realistic option or it has to be placed in the same directory where my main Steam app is installed?

By the way, If there is anyone in the future in the same situation, at least this is a way to avoid the issue.

**Comment by moraroy** [comment]
@samdevega oh ok I see so the issue isn't with the launcher then, its simply where youre putting your games, right?

**Comment by moraroy** [comment]
@samdevega here is the old github, I think its the same fix that youre describing https://github.com/scawp/Steam-Deck.Mount-External-Drive

**Comment by samdevega** [comment]
Yes, it looks quite similar. Like I said, I was able to use the secondary disk location directly for Epic Games launcher, but found this issue only with GOG.

**Comment by moraroy** [comment]
@samdevega hey I was thinking of how to fix this automatically for everyone, couldn't I put a bunch of broken symlinks in that folder so other mounts and partitions use it, if they needed it?

**Comment by msmirle** [comment]
> I found a workaround to deal with the issue. Instead of trying to set the games installation folder directly to a folder in the secondary disk, I created a symlink in the primary disk within the compatdata folder (~/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser) so now there is a new "folder" called Games that points to the Steam library folder in the secondary disk (/mnt/games/SteamLibrary/steamapps/common). Rest of folders are pointing to games installation folder by default.
> 
> Could I suggest to include an extra option in the NSL install menu to choose where do you want to install the launchers so their downloads folders will be in the desired disk? Is that a realistic option or it has to be placed in the same directory where my main Steam app is installed?
> 
> By the way, If there is anyone in the future in the same situation, at least this is a way to avoid the issue.

Thanks so much for posting this. I have the same issue: I want to install games on my separate BTRFS partition. Everything works perfectly with Epic and Battle.net, but GOG reports the disk space issue.

My sym link mapping is as follows:
/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser/Games **(symlink)**
->
/mnt/games/GOG Galaxy **(desination on BTRFS partition)**

For some reason it's not solving the situation. I've already verified that the symlink is working as expected in the file manager.

Is there anything else that you did aside from the symlink to make this work (permissions, etc.)?

**Comment by samdevega** [comment]
> [@samdevega](https://github.com/samdevega) hey I was thinking of how to fix this automatically for everyone, couldn't I put a bunch of broken symlinks in that folder so other mounts and partitions use it, if they needed it?

That could work, I guess. It's worth a try.

**Comment by samdevega** [comment]
> > I found a workaround to deal with the issue. Instead of trying to set the games installation folder directly to a folder in the secondary disk, I created a symlink in the primary disk within the compatdata folder (~/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser) so now there is a new "folder" called Games that points to the Steam library folder in the secondary disk (/mnt/games/SteamLibrary/steamapps/common). Rest of folders are pointing to games installation folder by default.
> > Could I suggest to include an extra option in the NSL install menu to choose where do you want to install the launchers so their downloads folders will be in the desired disk? Is that a realistic option or it has to be placed in the same directory where my main Steam app is installed?
> > By the way, If there is anyone in the future in the same situation, at least this is a way to avoid the issue.
> 
> Thanks so much for posting this. I have the same issue: I want to install games on my separate BTRFS partition. Everything works perfectly with Epic and Battle.net, but GOG reports the disk space issue.
> 
> My sym link mapping is as follows: /home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser/Games **(symlink)** -> /mnt/games/GOG Galaxy **(desination on BTRFS partition)**
> 
> For some reason it's not solving the situation. I've already verified that the symlink is working as expected in the file manager.
> 
> Is there anything else that you did aside from the symlink to make this work (permissions, etc.)?

Hi,

Yes, there is something.
When creating the secondary disk partition, be sure to check **Permissions** to **Everyone**, so launchers can read/write into the secondary disk. Here you have an [Screenshot](https://linuxbsdos.com/wp-content/uploads/2025/03/kde-disk-4-441x512.webp).
I also found that sometimes I had an error when mounting the secondary disk on system startup. It was fixed after choosing disk identify method to its UUID.

Hope it helps you.

**Comment by msmirle** [comment]
> > > I found a workaround to deal with the issue. Instead of trying to set the games installation folder directly to a folder in the secondary disk, I created a symlink in the primary disk within the compatdata folder (~/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser) so now there is a new "folder" called Games that points to the Steam library folder in the secondary disk (/mnt/games/SteamLibrary/steamapps/common). Rest of folders are pointing to games installation folder by default.
> > > Could I suggest to include an extra option in the NSL install menu to choose where do you want to install the launchers so their downloads folders will be in the desired disk? Is that a realistic option or it has to be placed in the same directory where my main Steam app is installed?
> > > By the way, If there is anyone in the future in the same situation, at least this is a way to avoid the issue.
> > 
> > 
> > Thanks so much for posting this. I have the same issue: I want to install games on my separate BTRFS partition. Everything works perfectly with Epic and Battle.net, but GOG reports the disk space issue.
> > My sym link mapping is as follows: /home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser/Games **(symlink)** -> /mnt/games/GOG Galaxy **(desination on BTRFS partition)**
> > For some reason it's not solving the situation. I've already verified that the symlink is working as expected in the file manager.
> > Is there anything else that you did aside from the symlink to make this work (permissions, etc.)?
> 
> Hi,
> 
> Yes, there is something. When creating the secondary disk partition, be sure to check **Permissions** to **Everyone**, so launchers can read/write into the secondary disk. Here you have an [Screenshot](https://linuxbsdos.com/wp-content/uploads/2025/03/kde-disk-4-441x512.webp). I also found that sometimes I had an error when mounting the secondary disk on system startup. It was fixed after choosing disk identify method to its UUID.
> 
> Hope it helps you.

Appreciate this. I executed the following command on the secondary drive (which I thought fully opened up permissions) but still not working unfortunately:
sudo chmod -R 777 /mnt/games/

**Comment by samdevega** [comment]
> Appreciate this. I executed the following command on the secondary drive (which I thought fully opened up permissions) but still not working unfortunately: sudo chmod -R 777 /mnt/games/

Just for being sure, are you selecting the symlink folder or de original secondary disk folder as download games folder in Gog Galaxy Setttings? You should be selecting the symlink folder.

Apart from that, I didn't have to do anything else in order to make it work.

**Comment by msmirle** [comment]
> > Appreciate this. I executed the following command on the secondary drive (which I thought fully opened up permissions) but still not working unfortunately: sudo chmod -R 777 /mnt/games/
> 
> Just for being sure, are you selecting the symlink folder or de original secondary disk folder as download games folder in Gog Galaxy Setttings? You should be selecting the symlink folder.
> 
> Apart from that, I didn't have to do anything else in order to make it work.

Yep I'm selecting the symlink folder which points to the secondary BTRFS drive. I'm going to give up and just use Heroic for GOG. All the other launchers installed via non-steam launchers work perfectly and I'm very familiar with symlinks so something must be fundamentally wrong with my BTRFS config.

Thanks again for your help!

**Comment by oliveirarafa** [comment]
I'm having a similar problem with my ubisoft app. Can't install because it says I dont have enough space. Tried the above method of symlink but it still dont recognize my free space on the second partition.

**Comment by msmirle** [comment]
> I'm having a similar problem with my ubisoft app. Can't install because it says I dont have enough space. Tried the above method of symlink but it still dont recognize my free space on the second partition.

I actually didn't install the Ubisoft launcher yet. Have you tried any other launchers like Battle.net, Epic Game Store? I can confirm it works with Battle.net and Epic, but not with GOG. Maybe Ubisoft is also problematic?

**Comment by oliveirarafa** [comment]
> > I'm having a similar problem with my ubisoft app. Can't install because it says I dont have enough space. Tried the above method of symlink but it still dont recognize my free space on the second partition.
> 
> I actually didn't install the Ubisoft launcher yet. Have you tried any other launchers like Battle.net, Epic Game Store? I can confirm it works with Battle.net and Epic, but not with GOG. Maybe Ubisoft is also problematic?

Yeah, I only installed EPIC and it worked. The others I didn't use yet.

**Comment by msmirle** [comment]
> > > I'm having a similar problem with my ubisoft app. Can't install because it says I dont have enough space. Tried the above method of symlink but it still dont recognize my free space on the second partition.
> > 
> > 
> > I actually didn't install the Ubisoft launcher yet. Have you tried any other launchers like Battle.net, Epic Game Store? I can confirm it works with Battle.net and Epic, but not with GOG. Maybe Ubisoft is also problematic?
> 
> Yeah, I only installed EPIC and it worked. The others I didn't use yet.

Ok - would be interesting to see if you have the same problem that I have with GOG Galaxy. I'll give Ubisoft launcher a try and update with the result.

**Comment by oliveirarafa** [comment]
Well, I tried with GOG and when installing using a symlink it worked, but when installing directly to my other driver I got an error.

**Comment by msmirle** [comment]
Interesting. I'll have to tinker more this upcoming weekend.

Honestly Heroic is doing the job just fine for GoG, Epic, and Amazon for me. This NonSteamLaunchers solution is for the other launchers, of which I only really care about Battle.net and Ubisoft b/c they can install PC gamepass games.

**Comment by oliveirarafa** [comment]
I fixed the storage issue by moving the nonsteamlaunchers folder to my larger partition and creating symbolic links in compatdata. Now, Ubisoft and GOG games install there by default without any issues.

**Comment by msmirle** [comment]
> I fixed the storage issue by moving the nonsteamlaunchers folder to my larger partition and creating symbolic links in compatdata. Now, Ubisoft and GOG games install there by default without any issues.

Hey that worked - thanks for the update! I never thought to symlink both the install location as well as the actual location of the NonSteamLaunhcers compatdata folder!

I assume most people don't experience this if they're just installing on the same drive.

**Comment by moraroy** [comment]
@SpazShark what would be the best way to fix this for you guys automatically? I was thinking of placing broken symlinks on purpose to allow your partitions to recognize the paths.

**Comment by msmirle** [comment]
To fix this I did the following:
1) Created a symlink inside the NonSteamLaunchers proton prefix located at "C:\users\steamuser\Games" and pointed to my games partition (/var/mnt/games).
2) Moved the proton prefix folder for NonSteamLaunchers (the actual numerically named folder, not the NonSteamLaunchers symlink) to my games partition. Created a symlink with the numerically named folder pointing to the new location.

Hope this makes sense. I'm not sure how you automate this but both of these steps were required for me.

Great work on this app BTW! I appreciate all the work that you've done.

EDIT: To put it simply, the fix was to make sure that the NonSteamLaunchers proton prefix folder was located on the same separate BTRFS drive that I wanted to install to. Maybe you can allow users to choose which drive they want to NonSteamLaunchers prefix folder to be installed on?

**Comment by ameeno** [comment]
I encountered an issue where the installer incorrectly reported only 7GB of free space (likely reading from the root partition). To fix this and ensure the installer sees the correct disk capacity, I performed the following:

Used Protontricks on the NonSteamLaunchers prefix to open winecfg.

Mapped an H: drive pointing to /home/deck.

Installed the game into subfolders within this new H: drive.

This forces the prefix to recognize the actual capacity of the home partition, preventing "insufficient disk space" errors during installation.
